# Change these first
owner: Frostist # Your GitHub organization or username, where this repository lives
repo: WebsiteWatcher # The name of this repository

sites:
  - name: Perffin Framer Site
    url: https://www.perffingroup.com
  - name: Britalian Site
    url: https://britalian.co.za
  - name: Qrescendo Site
    url: https://qrescendo.co
  - name: Secret Network
    url: https://scrt.network
  - name: Will Frost Site
    url: https://willfrost.co.za
  - name: Learning2Learn
    url: https://learning2learn.africa
  - name: Lisa Loud
    url: https://lisaloud.com
  - name: Fluidefi
    url: https://fluidefi.com
  - name: Edunova
    url: https://lms.edunova.org
  - name: XLCareers
    url: https://xlcareers.co.za
  - name: MailServer
    url: https://mailserver.qrescendo.co
  - name: Perffin API
    url: https://perffin-stock.britalian.workers.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: dark
  baseUrl: Frostist/britalianuptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Britalian UpTime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Britalian
      href: https://britalian.co.za
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
